server:
  port: 9000

spring:
  application:
    name: spring-ai

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-ai
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
    properties:
      hibernate:
        dialect:
        format_sql:

  # OPENAI config
  #  ai:
  #    openai:
  #      api-key: ${OPENAI_API_KEY}
  #      chat:
  #        options:
  #          model: gpt-4.0-mini

  # GEMINI config
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-3-flash-preview

        memory:
          repository:
            jdbc:
              initialize-schema: always